In [110]:
import numpy as np
import pandas as pd


In [111]:
print(np.__version__)
print(pd.__version__)

1.21.2
1.3.2


In [112]:

mydata = pd.read_csv("data.csv")

In [113]:
mydata.head(10)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   
5  BMW    1 Series  2012  premium unleaded (required)      230.0   
6  BMW    1 Series  2012  premium unleaded (required)      300.0   
7  BMW    1 Series  2012  premium unleaded (required)      300.0   
8  BMW    1 Series  2012  premium unleaded (required)      230.0   
9  BMW    1 Series  2013  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   
5               6.0            MANUAL  rear wheel drive              2.0   
6               6.0            MANUAL  rear wheel drive              2.0   
7               6.0            MANUAL  rear wheel drive              2.0   
8               6.0            MANUAL  rear wheel drive              2.0   
9               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   
5                     Luxury,Performance      Compact         Coupe   
6                     Luxury,Performance      Compact   Convertible   
7                Luxury,High-Performance      Compact         Coupe   
8                                 Luxury      Compact   Convertible   
9                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500  
5           28        18        3916  31200  
6           26        17        3916  44100  
7           28        20        3916  39300  
8           28        18        3916  36900  
9           27        18        3916  37200

In [131]:
mydata.groupby("Make") .MSRP.mean()

Make
Acura            3.488759e+04
Alfa Romeo       6.160000e+04
Aston Martin     1.979104e+05
Audi             5.345211e+04
BMW              6.154676e+04
Bentley          2.471693e+05
Bugatti          1.757224e+06
Buick            2.820661e+04
Cadillac         5.623132e+04
Chevrolet        2.835039e+04
Chrysler         2.672296e+04
Dodge            2.239006e+04
FIAT             2.267024e+04
Ferrari          2.382188e+05
Ford             2.739927e+04
GMC              3.049330e+04
Genesis          4.661667e+04
HUMMER           3.646441e+04
Honda            2.667434e+04
Hyundai          2.459704e+04
Infiniti         4.239421e+04
Kia              2.531017e+04
Lamborghini      3.315673e+05
Land Rover       6.782322e+04
Lexus            4.754907e+04
Lincoln          4.283983e+04
Lotus            6.918828e+04
Maserati         1.142077e+05
Maybach          5.462219e+05
Mazda            2.003938e+04
McLaren          2.398050e+05
Mercedes-Benz    7.147623e+04
Mitsubishi       2.124054e+04
Nissa

In [115]:
mydata[
    mydata["Year"] >= 2015
].describe().round()

Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
count  5995.0     5944.0            5987.0           5990.0       5995.0   
mean   2016.0      273.0               5.0              4.0         29.0   
std       1.0      109.0               2.0              1.0         10.0   
min    2015.0       66.0               0.0              2.0         13.0   
25%    2015.0      184.0               4.0              4.0         24.0   
50%    2016.0      270.0               6.0              4.0         28.0   
75%    2017.0      325.0               6.0              4.0         33.0   
max    2017.0      750.0              12.0              4.0        354.0   

       city mpg  Popularity      MSRP  
count    5995.0      5995.0    5995.0  
mean       22.0      1759.0   45667.0  
std        11.0      1443.0   40051.0  
min        10.0        21.0   11990.0  
25%        17.0       640.0   26910.0  
50%        20.0      1439.0   35845.0  
75%        24.0      2031.0   48105.0  
max       137.0      5657.0  548800.0

In [116]:
mydata[
    mydata["Year"] >= 2015
].isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [117]:
print(round(mydata["Engine HP"].mean()))

249


In [118]:
mydata["Engine HP"] = mydata["Engine HP"].fillna(mydata["Engine HP"].mean())

In [119]:
mydata[
    mydata["Year"] >= 2015
].isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP               0
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [120]:
print(round(mydata["Engine HP"].mean()))

249


In [121]:
mydata[
    mydata["Make"] == "Rolls-Royce"
][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [122]:
x = mydata[
    mydata["Make"] == "Rolls-Royce"
][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates().to_numpy()
print(x)
print(x.shape)

[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]
(7, 3)


In [123]:
xT = x.T
print(xT)
print(xT.shape)


[[325. 563. 563. 563. 322. 453. 624.]
 [  8.  12.  12.  12.  12.  12.  12.]
 [ 15.  19.  21.  20.  15.  19.  21.]]
(3, 7)


In [128]:
xTx = xT.dot(x)
xTx
inv = np.linalg.inv(xTx)
print(inv)
inv.sum()

[[ 5.17815728e-05  9.06587044e-04 -1.92984188e-03]
 [ 9.06587044e-04  1.05723058e-01 -8.87084092e-02]
 [-1.92984188e-03 -8.87084092e-02  1.05900809e-01]]


0.032212320677486125

In [125]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
print(y)

[1000 1100  900 1200 1000  850 1300]


In [127]:
w1 = inv.dot(xT)
w = w1.dot(y)
print(w[0])

0.19989598183188972
